##########################################################################################################
#                                                                                                        #
#                                       SwornRPG Configuration File                                      #
#                                           Created by dmulloy2                                          #
#  Detailed explanation here: http://dev.bukkit.org/server-mods/swornrpg/pages/sworn-rpg-configuration/  #
#                                                                                                        #
##########################################################################################################

debug: false
# Enable/disable extra logging to console

updatechecker: true
# Enable/disable checking for updates

irondoorprotect: true
# Enable/disable the protection of iron doors

randomdrops: true
# Enable/disable the random chance that a random drop will drop from a block

axekb: true
# Enable/disable the random chance that players can get knocked back by axes

arrowfire: true
# Enable/disable the random chance that players can catch fire when shot by arrows

deathbook: true
# Will a player receive a book/message with their death coordinates?
# If essentials is found, the plugin will send a mail message. If not, it will give a book

marriage: true
# Enable/disable marriage

campingradius: 16
# If a player is within x radius of a mob spawner, cancel xp gain

salvaging: true
# Enable/disable salvaging

redeem-enabled: true
# Enable/disable block redemption

salvage: "306, Iron, 5; 307, Iron, 8; 308, Iron, 7; 309, Iron, 4; 310, Diamond, 5; 311, Diamond, 8; 312, Diamond, 7; 313, Diamond, 4; 314, Gold, 5; 315, Gold, 8; 316, Gold, 7; 317, Gold, 4; 267, Iron, 2; 256, Iron, 1; 257, Iron, 3; 258, Iron, 3; 292, Iron, 2; 276, Diamond, 2; 277, Diamond, 1; 278, Diamond, 3; 279, Diamond, 3; 293, Diamond, 2; 283, Gold, 2; 284, Gold, 1; 285, Gold, 3; 286, Gold, 3; 294, Gold, 2"
# Items that can be salvaged, formatted: "id, Material, how many items it returns; ...; lastid, Lastmaterial, lastitems"

autosave:
  enabled: true
  interval: 15
# AutoSave task. Interval in minutes.
  
frenzy:
  enabled: true
  # Is frenzy mode enabled?
  baseduration: 5
  # Frenzy base duration (Formula = frenzy base duraton + (level multiplier x level))
  levelmultiplier: 1
  cooldownmultiplier: 10
  # Frenzy cooldown multiplier (Formula = duration x cooldown multiplier)
  
superpickaxe:
  enabled: true
  # Is super pickaxe ability enabled?
  baseduration: 10
  # Super pick base duration (Formula = base duraton + (level multiplier x level))
  levelmultiplier: 2
  cooldownmultiplier: 2
  # Super pick cooldown multiplier (Formula = duraton x cooldown multiplier)
 
unlimitedammo:
  enabled: true
  # Is unlimited ammo ability enabled?
  baseduration: 10
  # Unlimited ammo base duration (Formula = base duraton + (level multiplier x level))
  levelmultiplier: 2
  cooldownmultiplier: 2
  # Unlimited ammo cooldown multiplier (Formula = duraton x cooldown multiplier)

levelingmethods:
# How can players level up?
  mcxpgain:
    enabled: true
    xpgain: 15
    # How much xp a player gains when they level up using MC xp
  playerkills:
    enabled: true
    xpgain: 25
    # Xp gained when a player kills
    xploss: 10
    # Xp lost when a player dies
  mobkills:
    enabled: true
    xpgain: 5
    # Xp gain when a player kills a mob
  onlinetime:
    enabled: true
    xpgain: 1
    # Xp gained per minute of online time
  taming:
    enabled: true
    xpgain: 5
    # Xp gain when a player tames a mob
  fishing:
    enabled: true
    xpgain: 5
    # Xp gain when a player catches a fish
  herbalism:
    enabled: true
    xpgain: 1
    # Xp gain when a player farms (per crop)
  enchanting:
    enabled: true
    xpgain: 5
    # Xp gain multiplier (Formula = (enchanting cost / 2) + multiplier)

levelingrewards:
# What do players receive for leveling up?
  money:
    enabled: true
    amountperlevel: 250
  items:
    enabled: true
    itemid: 264
    # Item id of the item you wish to reward (Defaults to diamond)
    amountperlevel: 1
    
healthtags:
# Mob health tags
  enabled: true
  
playerhealth:
# Player health tags
  enabled: true
  
disabled-worlds:
# Worlds SwornRPG is disabled in
- disabled_world

confusion:
# Confusion when a player punches another player in the face
  enabled: true
  duration: 3
  # Duration in seconds
    
block-drops:
# Configure rare drops here
# Format: - "itemid:chance"
  0:
    - "2258:10000"
    - "2267:10000"
    - "2262:10000"
    - "2263:10000"
    - "2264:10000"
    - "2265:10000"
    - "264:1000"
    - "384:5000"
    - "399:50000"
    - "266:1000"
    - "265:1000"
  82:
    - "341:20"
    - "287:20"
    - "318:20"
    - "30:100"
  2:
    - "361:30"
    - "392:30"
    - "391:30"
  1:
    - "15:75"
    - "16:25"
    - "14:200"
  17:
    - "338:20"
    - "32:200"
    - "127:100"
  4:
    - "389:20"
    - "145:200"
    - "386:100"
  121:
    - "116:150"
    - "388:100"
    - "368:25"
  87:
    - "385:15"
    - "372:25"
    - "112:10"
    - "406:10"
  3:
    - "392:30"
    - "357:30"
    - "395:100"
    - "330:100"
  13:
    - "289:15"
    - "352:10"
    - "87:50"

fish-drops:
# Items dropped when fishing
# Format: - "itemid:chance"
# Done by player level (Cap is at level 10 for fish drops)
  0:
    - "301:10"
    - "268:5"
  1:
    - "269:5"
    - "346:10"
  2:
    - "270:15"
    - "298:5"
  3:
    - "300:5"
    - "271:5"
  4:
    - "290:5"
    - "291:15"
  5:
    - "273:10"
    - "275:5"
  6:
    - "272:15"
    - "274:15"
    
redeem-blacklist:
# Blacklisted Materials for Building redeem
- beacon
- diamond_block
- iron_block
- gold_block